@extends('layouts.app')
@section('title','SKILLPATH | Course Nonakademik Anak')
@section('content')
<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">Course nonakademik usia 5–14 tahun</span><h1>Belajar skill baru bersama <span>pengajar pilihan.</span></h1><p class="hero-lead">Pilih course Arts, Languages, Music, Sports, dan Technology. Anak dapat belajar melalui modul mandiri, aktivitas praktik, atau live class bersama pengajar.</p><div class="hero-actions"><a class="btn btn-dark" href="{{ route('explore.index') }}">Jelajah Course</a><a class="btn btn-ghost" href="{{ route('instructors.index') }}">Lihat Pengajar</a></div><div class="trust-row"><span>✓ Usia 5–14</span><span>✓ Pengajar terverifikasi</span><span>✓ Live class & rekaman</span><span>✓ Laporan progres</span></div></div><div class="hero-stage"><div class="learning-board"><p class="board-kicker">SKILLPATH CLASS</p><h2>Course sesuai usia, minat, dan tujuan anak.</h2><div class="board-tags"><span>Video</span><span>Live Class</span><span>Project</span></div><div class="board-progress"><div style="width:72%"></div></div><small>Belajar bertahap. Progres tersimpan.</small></div><div class="skillbot"><div class="bot-ear left"></div><div class="bot-ear right"></div><div class="bot-head"><div class="bot-face"><span class="bot-eye"></span><span class="bot-eye"></span><span class="bot-smile"></span></div></div><div class="bot-body"><span>S</span></div><div class="bot-leg left"></div><div class="bot-leg right"></div></div></div></div></section>
<section class="section category-home-section"><div class="container"><div class="section-heading split-heading"><div><span class="eyebrow">Kategori</span><h2>Pilih bidang yang anak sukai.</h2></div><a class="text-link" href="{{ route('categories.index') }}">Semua kategori →</a></div><div class="category-grid category-grid-home">@foreach($categories as $category)<a class="category-card" href="{{ route('explore.index',['category'=>$category->slug]) }}"><div class="category-icon">{{ $category->icon }}</div><div class="category-card-copy"><span class="category-count">{{ $category->learning_paths_count }} course</span><h3>{{ $category->name }}</h3><p>{{ $category->description }}</p><span class="category-link">Jelajahi →</span></div></a>@endforeach</div></div></section>
<section class="section section-soft"><div class="container"><div class="section-heading split-heading"><div><span class="eyebrow">Course Pilihan</span><h2>Belajar dari aktivitas yang terstruktur.</h2></div><a class="text-link" href="{{ route('explore.index') }}">Lihat semua →</a></div><div class="course-market-grid">@foreach($featuredPaths as $path)<article class="market-course-card"><div class="course-thumb"><span>{{ $path->icon }}</span><small>{{ strtoupper(str_replace('_',' ',$path->course_type)) }}</small></div><div class="course-card-body"><h2>{{ $path->title }}</h2><p class="teacher-line">oleh {{ $path->instructor?->name ?? 'Tim SKILLPATH' }}</p><div class="rating-line"><strong>{{ number_format((float)($path->reviews->avg('rating')??0),1) }}</strong><span>★</span><small>{{ $path->enrollments_count }} peserta</small></div><div class="course-price-row"><strong>{{ $path->is_free?'Gratis':'Rp'.number_format($path->effectivePrice(),0,',','.') }}</strong></div><a class="btn btn-dark btn-full" href="{{ route('courses.show',$path) }}">Lihat Course</a></div></article>@endforeach</div></div></section>
<section class="section"><div class="container"><div class="section-heading"><span class="eyebrow">Pengajar</span><h2>Kenali siapa yang mendampingi anak.</h2></div><div class="instructor-grid">@foreach($featuredInstructors as $i)<article class="instructor-list-card"><div class="teacher-avatar xlarge">{{ strtoupper(substr($i->name,0,1)) }}</div><div><h2>{{ $i->name }}</h2><p>{{ $i->instructorProfile?->headline }}</p><div class="path-meta"><span>★ {{ $i->instructorProfile?->rating }}</span><span>{{ $i->courses_taught_count }} course</span></div><a class="card-link" href="{{ route('instructors.show',$i) }}">Lihat profil →</a></div></article>@endforeach</div></div></section>
<section class="section parent-section"><div class="container parent-grid"><div><span class="eyebrow">Untuk Orang Tua</span><h2>Pantau pembelian dan perkembangan belajar.</h2><p>Orang tua mengelola profil anak, membeli course, melihat progres, live class, sertifikat, dan riwayat transaksi dari satu akun.</p><a class="btn btn-blue" href="{{ route('parents') }}">Pelajari Dashboard Orang Tua</a></div><div class="parent-panel"><div class="mini-stat"><strong>Course</strong><span>pilih sesuai minat</span></div><div class="mini-stat"><strong>Live</strong><span>jadwal bersama pengajar</span></div><div class="mini-stat"><strong>Report</strong><span>progres anak</span></div></div></div></section>
@endsection
