@extends('admin.layouts.app')
@section('title','Detail Kehadiran | Admin SKILLPATH')
@section('page-title','Detail Kehadiran')
@section('content')
<div class="admin-page-toolbar"><a class="admin-btn ghost" href="{{ route('admin.attendance.index') }}">← Kehadiran Peserta</a><span class="admin-status {{ $summary['status'] }}">{{ $summary['status_label'] }}</span></div>
<div class="admin-stat-grid"><x-admin.metric-card label="Kelas Terdaftar" :value="$summary['enrollment_count']" /><x-admin.metric-card label="Sesi Dihadiri" :value="$summary['attended_count']" /><x-admin.metric-card label="Tidak Hadir" :value="$summary['absent_count']" /><x-admin.metric-card label="Tingkat Kehadiran" :value="($summary['attendance_rate']??0).'%'" /></div>
<section class="admin-section-card"><x-admin.section-header eyebrow="Peserta" :title="$childProfile->name" :description="($childProfile->age.' tahun · Orang tua: '.($childProfile->user?->name ?? '—'))" />
<div class="admin-table-shell"><table class="admin-table"><thead><tr><th>Kelas</th><th>Jadwal</th><th>Hadir</th><th>Tidak Hadir</th><th>Kehadiran</th></tr></thead><tbody>@foreach($courseAttendance as $row)<tr><td><strong>{{ $row['path']->title }}</strong><small class="admin-cell-help">{{ $row['path']->instructor?->name }}</small></td><td>{{ $row['session_count'] }} sesi <small class="admin-cell-help">{{ $row['upcoming_count'] }} mendatang</small></td><td>{{ $row['attended_count'] }}</td><td>{{ $row['absent_count'] }}</td><td>{{ $row['attendance_rate']!==null?$row['attendance_rate'].'%':'—' }}</td></tr>@endforeach</tbody></table></div></section>
<section class="admin-section-card"><x-admin.section-header eyebrow="Riwayat" title="Booking dan kehadiran" description="Status sesi tatap muka yang pernah dipesan peserta." /><div class="admin-table-shell"><table class="admin-table"><thead><tr><th>Tanggal</th><th>Kelas & Sesi</th><th>Lokasi</th><th>Status</th><th>Catatan</th></tr></thead><tbody>@forelse($bookings as $booking)<tr><td>{{ $booking->classSession?->starts_at?->translatedFormat('d M Y H:i') }}</td><td><strong>{{ $booking->classSession?->learningPath?->title }}</strong><small class="admin-cell-help">{{ $booking->classSession?->title }}</small></td><td>{{ $booking->classSession?->venue_name }}</td><td><span class="admin-status {{ $booking->status }}">{{ strtoupper($booking->status) }}</span></td><td>{{ $booking->notes ?: '—' }}</td></tr>@empty<tr><td colspan="5">Belum ada booking.</td></tr>@endforelse</tbody></table></div></section>
@endsection
