@extends('layouts.app')
@section('title','Kelola Kelas | SKILLPATH')
@section('content')
<section class="simple-hero"><div class="container"><span class="eyebrow">Kelola Kelas Offline</span><h1>{{ $learningPath->title }}</h1></div></section>
<section class="section"><div class="container two-column-section"><div>
<div class="content-card"><h2>Informasi penjualan & program</h2><form method="POST" action="{{ route('instructor.courses.update',$learningPath) }}" class="form-stack">@csrf @method('PUT')
<label><span>Harga</span><input type="number" name="price" min="0" value="{{ old('price',$learningPath->price) }}" required></label>
<label><span>Harga promo</span><input type="number" name="sale_price" min="0" value="{{ old('sale_price',$learningPath->sale_price) }}"></label>
<label><span>Tipe kelas</span><select name="class_type"><option value="regular" @selected($learningPath->class_type==='regular')>Kelas Rutin</option><option value="workshop" @selected($learningPath->class_type==='workshop')>Workshop</option><option value="private" @selected($learningPath->class_type==='private')>Privat</option></select></label>
<label><span>Area / lokasi umum</span><input name="venue_summary" maxlength="180" value="{{ old('venue_summary',$learningPath->venue_summary) }}" placeholder="Contoh: Panakkukang, Makassar"></label>
<label><span>Keterampilan yang dikembangkan</span><textarea name="learning_outcomes" rows="5">{{ old('learning_outcomes',$learningPath->learning_outcomes) }}</textarea></label>
<label><span>Perlengkapan yang disediakan</span><textarea name="materials_included" rows="4">{{ old('materials_included',$learningPath->materials_included) }}</textarea></label>
<label><span>Yang perlu dibawa / persyaratan</span><textarea name="requirements" rows="4">{{ old('requirements',$learningPath->requirements) }}</textarea></label>
<button class="btn btn-dark" type="submit">Simpan Kelas</button></form></div></div>
<div><div class="content-card"><h2>Buat jadwal tatap muka</h2><form method="POST" action="{{ route('instructor.schedules.store',$learningPath) }}" class="form-stack">@csrf
<label><span>Judul sesi</span><input name="title" required></label><label><span>Deskripsi</span><textarea name="description" rows="3"></textarea></label><label><span>Mulai</span><input type="datetime-local" name="starts_at" required></label><label><span>Selesai</span><input type="datetime-local" name="ends_at" required></label><label><span>Nama lokasi</span><input name="venue_name" required placeholder="Studio / gedung / lapangan"></label><label><span>Alamat</span><textarea name="address" rows="3" required></textarea></label><label><span>Ruangan / titik temu</span><input name="room"></label><label><span>Link peta</span><input type="url" name="map_url"></label><label><span>Kapasitas</span><input type="number" name="capacity" value="20" min="1" max="500" required></label><label><span>Catatan persiapan</span><textarea name="preparation_notes" rows="3" placeholder="Perlengkapan, pakaian, waktu datang, dll."></textarea></label><button class="btn btn-blue" type="submit">Tambah Jadwal</button></form></div>
<div class="content-card"><h2>Jadwal kelas</h2>@forelse($learningPath->classSessions as $session)<div class="schedule-row"><div><strong>{{ $session->title }}</strong><span>{{ $session->starts_at->translatedFormat('d M Y H:i') }} · {{ $session->venue_name }}</span><small>{{ $session->bookings->whereIn('status',['booked','attended'])->count() }}/{{ $session->capacity }} peserta · {{ strtoupper($session->status) }}</small></div><div><a class="text-button" href="{{ route('instructor.schedules.show',$session) }}">Kehadiran</a>@if($session->bookings->whereIn('status',['booked','attended'])->isEmpty())<form method="POST" action="{{ route('instructor.schedules.destroy',$session) }}">@csrf @method('DELETE')<button class="text-button" type="submit">Hapus</button></form>@endif</div></div>@empty<p>Belum ada jadwal.</p>@endforelse</div>
</div></div></section>
@endsection
