@extends('admin.layouts.app')
@section('title','Dashboard Admin | SKILLPATH')
@section('page-title','Dashboard')
@section('content')
<div class="admin-welcome"><div><span class="admin-eyebrow">Ringkasan platform</span><h2>Selamat datang, {{ auth()->user()->name }}.</h2><p>Pantau kelas offline, transaksi, pengajar, peserta, jadwal, dan kehadiran dari satu halaman.</p></div><a class="admin-btn primary" href="{{ route('admin.courses.index') }}">Kelola Kelas</a></div>
<div class="admin-stat-grid">
<article class="admin-stat-card accent-yellow"><span class="admin-stat-label">Total Kelas</span><strong>{{ number_format($stats['courses']) }}</strong><small>{{ number_format($stats['published_courses']) }} dipublikasikan</small></article>
<article class="admin-stat-card accent-blue"><span class="admin-stat-label">Pengguna Orang Tua</span><strong>{{ number_format($stats['students']) }}</strong><small>{{ number_format($stats['enrollments']) }} pendaftaran aktif</small></article>
<article class="admin-stat-card accent-green"><span class="admin-stat-label">Pengajar</span><strong>{{ number_format($stats['instructors']) }}</strong><small>{{ number_format($stats['categories']) }} kategori kegiatan</small></article>
<article class="admin-stat-card accent-pink"><span class="admin-stat-label">Pendapatan Bulan Ini</span><strong>Rp{{ number_format($stats['revenue_this_month'],0,',','.') }}</strong><small>Total Rp{{ number_format($stats['revenue'],0,',','.') }}</small></article>
</div>
<div class="admin-dashboard-grid"><section class="admin-panel"><div class="admin-panel-head"><div><span class="admin-eyebrow">Transaksi</span><h2>Pesanan terbaru</h2></div><a href="{{ route('admin.orders.index') }}">Lihat semua →</a></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Nomor</th><th>Pembeli</th><th>Total</th><th>Status</th></tr></thead><tbody>@forelse($recentOrders as $order)<tr><td><a class="admin-table-link" href="{{ route('admin.orders.show',$order) }}">{{ $order->order_number }}</a></td><td>{{ $order->user->name }}</td><td>Rp{{ number_format($order->total,0,',','.') }}</td><td><span class="status-badge {{ $order->payment_status }}">{{ strtoupper($order->payment_status) }}</span></td></tr>@empty<tr><td colspan="4" class="admin-empty-cell">Belum ada transaksi.</td></tr>@endforelse</tbody></table></div></section>
<section class="admin-panel"><div class="admin-panel-head"><div><span class="admin-eyebrow">Kelas</span><h2>Paling banyak diikuti</h2></div></div><div class="admin-course-rank">@forelse($popularCourses as $course)<div class="admin-rank-item"><span class="admin-rank-icon">{{ $course->icon }}</span><div><strong>{{ $course->title }}</strong><small>{{ $course->instructor?->name ?? 'Belum ada pengajar' }}</small></div><span class="admin-rank-value">{{ $course->enrollments_count }}</span></div>@empty<p class="admin-muted">Belum ada pendaftaran.</p>@endforelse</div></section></div>
<section class="admin-panel admin-dashboard-schedule-panel"><div class="admin-panel-head"><div><span class="admin-eyebrow">Kelas tatap muka</span><h2>Jadwal terdekat</h2><p>{{ $stats['teaching_today'] }} sesi hari ini · {{ $stats['upcoming_teaching'] }} sesi akan datang.</p></div><a href="{{ route('admin.schedules.index') }}">Kelola jadwal →</a></div><div class="dashboard-schedule-list">@forelse($nextSchedules as $session)<div class="dashboard-schedule-item"><div class="dashboard-schedule-date"><strong>{{ $session->starts_at->format('d') }}</strong><span>{{ strtoupper($session->starts_at->translatedFormat('M')) }}</span></div><div><strong>{{ $session->title }}</strong><small>{{ $session->learningPath?->title ?? 'Kelas tidak tersedia' }} · {{ $session->instructor?->name ?? 'Pengajar tidak tersedia' }} · {{ $session->venue_name }}</small></div><div class="dashboard-schedule-time"><strong>{{ $session->starts_at->format('H:i') }}</strong><span class="status-badge {{ $session->status }}">{{ strtoupper($session->status) }}</span></div></div>@empty<p class="admin-muted">Belum ada jadwal kelas mendatang.</p>@endforelse</div></section>
<div class="admin-quick-grid">
<a href="{{ route('admin.courses.index') }}" class="admin-quick-card"><span>▤</span><strong>Kelas</strong><small>Publikasi dan katalog</small></a>
<a href="{{ route('admin.instructors.index') }}" class="admin-quick-card"><span>♙</span><strong>Pengajar</strong><small>Verifikasi profil</small></a>
<a href="{{ route('admin.attendance.index') }}" class="admin-quick-card"><span>✓</span><strong>Kehadiran Peserta</strong><small>{{ $stats['student_profiles'] }} peserta termonitor</small></a>
<a href="{{ route('admin.schedules.index') }}" class="admin-quick-card"><span>◷</span><strong>Jadwal Kelas</strong><small>{{ $stats['upcoming_teaching'] }} sesi akan datang</small></a>
<a href="{{ route('admin.revenue.index') }}" class="admin-quick-card"><span>Rp</span><strong>Laporan Pendapatan</strong><small>Analisis transaksi PAID</small></a>
<a href="{{ route('admin.certificates.index') }}" class="admin-quick-card"><span>◇</span><strong>Sertifikat</strong><small>{{ $stats['certificates'] }} sertifikat aktif</small></a>
<a href="{{ route('admin.statistics.index') }}" class="admin-quick-card"><span>▥</span><strong>Statistik Platform</strong><small>{{ $stats['active_students_30d'] }} peserta hadir 30 hari</small></a>
<a href="{{ route('admin.orders.index') }}" class="admin-quick-card"><span>▣</span><strong>Pesanan</strong><small>Status transaksi</small></a>
<a href="{{ route('admin.reviews.index') }}" class="admin-quick-card"><span>★</span><strong>Review</strong><small>{{ $stats['pending_reviews'] }} perlu moderasi</small></a>
<a href="{{ route('admin.recycle-bin.index') }}" class="admin-quick-card"><span>♲</span><strong>Recycle Bin</strong><small>{{ $stats['recycle_bin'] }} data dapat dipulihkan</small></a>
</div>
@endsection
