@extends('layouts.app')
@section('title','Dashboard Pengajar | SKILLPATH')
@section('content')
<section class="dashboard-hero"><div class="container dashboard-hero-grid"><div><span class="eyebrow">Dashboard Pengajar</span><h1>Halo, {{ auth()->user()->name }}.</h1><p>Kelola kelas offline, jadwal tatap muka, kehadiran, dan pertanyaan peserta.</p></div></div></section>
<section class="section dashboard-section"><div class="container"><div class="stat-grid"><article class="stat-card"><span>Kelas</span><strong>{{ $courses->count() }}</strong></article><article class="stat-card"><span>Peserta unik</span><strong>{{ $studentCount }}</strong></article><article class="stat-card"><span>Jadwal mendatang</span><strong>{{ $upcoming->count() }}</strong></article></div>
<div class="section-heading dashboard-heading"><span class="eyebrow">Kelas Saya</span><h2>Kelola program</h2></div><div class="instructor-course-table">@foreach($courses as $course)<div class="instructor-course-row"><div><strong>{{ $course->title }}</strong><span>{{ $course->enrollments_count }} peserta · {{ $course->reviews_count }} ulasan</span></div><a class="btn btn-ghost" href="{{ route('instructor.courses.edit',$course) }}">Kelola</a></div>@endforeach</div>
<div class="two-column-section"><div><div class="section-heading"><h2>Jadwal kelas mendatang</h2></div>@forelse($upcoming as $session)<div class="schedule-row"><div><strong>{{ $session->title }}</strong><span>{{ $session->learningPath->title }} · {{ $session->starts_at->translatedFormat('d M H:i') }}</span><small>📍 {{ $session->venue_name }} · {{ $session->bookings->whereIn('status',['booked','attended'])->count() }}/{{ $session->capacity }} peserta</small></div><a class="btn btn-ghost" href="{{ route('instructor.schedules.show',$session) }}">Peserta</a></div>@empty<p>Belum ada jadwal.</p>@endforelse</div><div><div class="section-heading"><h2>Pertanyaan peserta</h2></div>@foreach($questions as $q)<article class="question-card"><strong>{{ $q->learningPath->title }}</strong><p>{{ $q->question }}</p>@if($q->answers->isEmpty())<form method="POST" action="{{ route('instructor.questions.answer',$q) }}" class="form-stack">@csrf<textarea name="answer" rows="2" required placeholder="Jawab peserta..."></textarea><button class="btn btn-dark" type="submit">Jawab</button></form>@else<span class="done-label">✓ Sudah dijawab</span>@endif</article>@endforeach</div></div>
</div></section>
@endsection
