@extends('admin.layouts.app')
@section('title','Sertifikat | Admin SKILLPATH')
@section('page-title','Manajemen Sertifikat')
@section('content')
<x-admin.feature-header eyebrow="Dokumen Penyelesaian" title="Sertifikat kelas offline" description="Kelola sertifikat peserta yang menyelesaikan program tatap muka dengan kehadiran lengkap." :primary-href="route('admin.certificates.create')" primary-label="Terbitkan Sertifikat" :secondary-href="route('admin.certificates.export',request()->query())" secondary-label="Export CSV" />
<div class="admin-stat-grid"><x-admin.metric-card label="Total" :value="$stats['total']" /><x-admin.metric-card label="Aktif" :value="$stats['active']" /><x-admin.metric-card label="Dicabut" :value="$stats['revoked']" /><x-admin.metric-card label="Siap Diterbitkan" :value="$stats['eligible']" /></div>
<section class="admin-section-card"><form method="GET" class="admin-filter-panel"><div class="admin-filter-grid"><label class="admin-filter-field"><span>Cari</span><input type="search" name="q" value="{{ request('q') }}" placeholder="Nomor, peserta, orang tua, atau kelas"></label><label class="admin-filter-field"><span>Status</span><select name="status"><option value="">Semua status</option><option value="active" @selected(request('status')==='active')>Aktif</option><option value="revoked" @selected(request('status')==='revoked')>Dicabut</option></select></label><label class="admin-filter-field"><span>Kelas</span><select name="course_id"><option value="">Semua kelas</option>@foreach($courses as $course)<option value="{{ $course->id }}" @selected((string)request('course_id')===(string)$course->id)>{{ $course->title }}</option>@endforeach</select></label><label class="admin-filter-field"><span>Dari tanggal</span><input type="date" name="from" value="{{ request('from') }}"></label><label class="admin-filter-field"><span>Sampai tanggal</span><input type="date" name="to" value="{{ request('to') }}"></label></div><div class="admin-filter-actions"><button class="admin-btn primary" type="submit">Terapkan</button><a class="admin-btn ghost" href="{{ route('admin.certificates.index') }}">Reset</a></div></form>
<div class="admin-table-shell"><table class="admin-table admin-data-table"><thead><tr><th>Nomor</th><th>Peserta</th><th>Kelas</th><th>Kehadiran</th><th>Tanggal Terbit</th><th>Status</th><th></th></tr></thead><tbody>@forelse($certificates as $certificate)<tr><td><a class="admin-inline-link" href="{{ route('admin.certificates.show',$certificate) }}">{{ $certificate->certificate_number }}</a></td><td><strong>{{ $certificate->childProfile?->name ?? '—' }}</strong><small class="admin-cell-help">{{ $certificate->childProfile?->user?->name ?? 'Orang tua tidak tersedia' }}</small></td><td><strong>{{ $certificate->learningPath?->title ?? 'Kelas tidak tersedia' }}</strong><small class="admin-cell-help">{{ $certificate->learningPath?->instructor?->name ?? 'Pengajar tidak tersedia' }}</small></td><td>{{ $certificate->final_score!==null?number_format($certificate->final_score,0).'%':'—' }}</td><td>{{ $certificate->issued_at?->translatedFormat('d M Y') ?? '—' }}</td><td><span class="admin-status {{ $certificate->status }}">{{ $certificate->status==='active'?'AKTIF':'DICABUT' }}</span></td><td><a class="admin-btn small ghost" href="{{ route('admin.certificates.show',$certificate) }}">Detail</a></td></tr>@empty<tr><td colspan="7"><div class="admin-empty-state"><strong>Belum ada sertifikat.</strong><span>Terbitkan setelah program selesai dan kehadiran peserta lengkap.</span></div></td></tr>@endforelse</tbody></table></div><div class="admin-pagination">{{ $certificates->links() }}</div></section>
@endsection
